// Auto-generated by Supabase CLI / MCP. Do NOT edit manually.
// Rigenerare con: pnpm dlx supabase gen types typescript --project-id jtmbnmpggzbucmgglisw
// oppure via MCP: mcp__supabase__generate_typescript_types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.1";
  };
  public: {
    Tables: {
      app_settings: {
        Row: {
          branding: Json | null;
          id: number;
          maintenance_mode: boolean | null;
          page_content: Json | null;
          page_images: Json | null;
          promo_banner: Json | null;
          seo_settings: Json | null;
        };
        Insert: {
          branding?: Json | null;
          id?: number;
          maintenance_mode?: boolean | null;
          page_content?: Json | null;
          page_images?: Json | null;
          promo_banner?: Json | null;
          seo_settings?: Json | null;
        };
        Update: {
          branding?: Json | null;
          id?: number;
          maintenance_mode?: boolean | null;
          page_content?: Json | null;
          page_images?: Json | null;
          promo_banner?: Json | null;
          seo_settings?: Json | null;
        };
        Relationships: [];
      };
      collections: {
        Row: {
          created_at: string | null;
          description: string | null;
          id: string;
          is_active: boolean | null;
          name: string;
        };
        Insert: {
          created_at?: string | null;
          description?: string | null;
          id?: string;
          is_active?: boolean | null;
          name: string;
        };
        Update: {
          created_at?: string | null;
          description?: string | null;
          id?: string;
          is_active?: boolean | null;
          name?: string;
        };
        Relationships: [];
      };
      coupons: {
        Row: {
          code: string;
          created_at: string | null;
          discount_type: string;
          id: string;
          is_active: boolean | null;
          usage_limit: number | null;
          used_count: number | null;
          valid_until: string | null;
          value: number;
        };
        Insert: {
          code: string;
          created_at?: string | null;
          discount_type: string;
          id?: string;
          is_active?: boolean | null;
          usage_limit?: number | null;
          used_count?: number | null;
          valid_until?: string | null;
          value: number;
        };
        Update: {
          code?: string;
          created_at?: string | null;
          discount_type?: string;
          id?: string;
          is_active?: boolean | null;
          usage_limit?: number | null;
          used_count?: number | null;
          valid_until?: string | null;
          value?: number;
        };
        Relationships: [];
      };
      email_templates: {
        Row: {
          body_html: string;
          created_at: string | null;
          id: string;
          name: string;
          subject: string;
          updated_at: string | null;
        };
        Insert: {
          body_html: string;
          created_at?: string | null;
          id?: string;
          name: string;
          subject: string;
          updated_at?: string | null;
        };
        Update: {
          body_html?: string;
          created_at?: string | null;
          id?: string;
          name?: string;
          subject?: string;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      material_score_cache: {
        Row: {
          created_at: string | null;
          diagnosis_result: string;
          id: string;
          material_key: string;
          original_material: string;
          sustainability_score: number;
        };
        Insert: {
          created_at?: string | null;
          diagnosis_result: string;
          id?: string;
          material_key: string;
          original_material: string;
          sustainability_score: number;
        };
        Update: {
          created_at?: string | null;
          diagnosis_result?: string;
          id?: string;
          material_key?: string;
          original_material?: string;
          sustainability_score?: number;
        };
        Relationships: [];
      };
      order_items: {
        Row: {
          created_at: string;
          id: string;
          order_id: string;
          price_at_purchase: number;
          product_id: string | null;
          quantity: number;
          selected_size: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          order_id: string;
          price_at_purchase: number;
          product_id?: string | null;
          quantity?: number;
          selected_size: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          order_id?: string;
          price_at_purchase?: number;
          product_id?: string | null;
          quantity?: number;
          selected_size?: string;
        };
        Relationships: [
          {
            foreignKeyName: "order_items_order_id_fkey";
            columns: ["order_id"];
            isOneToOne: false;
            referencedRelation: "orders";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "order_items_product_id_fkey";
            columns: ["product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["id"];
          },
        ];
      };
      orders: {
        Row: {
          causale: string | null;
          created_at: string;
          guest_email: string | null;
          id: string;
          legacy_stripe_session_id: string | null;
          metadata: Json | null;
          payment_id: string | null;
          payment_method: string | null;
          return_label_url: string | null;
          return_status: string | null;
          shipping_address: Json | null;
          shippo_label_url: string | null;
          shippo_rate_id: string | null;
          shippo_shipment_id: string | null;
          status: string;
          total_amount: number;
          tracking_number: string | null;
          tracking_url: string | null;
          updated_at: string;
          user_id: string | null;
        };
        Insert: {
          causale?: string | null;
          created_at?: string;
          guest_email?: string | null;
          id?: string;
          legacy_stripe_session_id?: string | null;
          metadata?: Json | null;
          payment_id?: string | null;
          payment_method?: string | null;
          return_label_url?: string | null;
          return_status?: string | null;
          shipping_address?: Json | null;
          shippo_label_url?: string | null;
          shippo_rate_id?: string | null;
          shippo_shipment_id?: string | null;
          status?: string;
          total_amount?: number;
          tracking_number?: string | null;
          tracking_url?: string | null;
          updated_at?: string;
          user_id?: string | null;
        };
        Update: {
          causale?: string | null;
          created_at?: string;
          guest_email?: string | null;
          id?: string;
          legacy_stripe_session_id?: string | null;
          metadata?: Json | null;
          payment_id?: string | null;
          payment_method?: string | null;
          return_label_url?: string | null;
          return_status?: string | null;
          shipping_address?: Json | null;
          shippo_label_url?: string | null;
          shippo_rate_id?: string | null;
          shippo_shipment_id?: string | null;
          status?: string;
          total_amount?: number;
          tracking_number?: string | null;
          tracking_url?: string | null;
          updated_at?: string;
          user_id?: string | null;
        };
        Relationships: [];
      };
      products: {
        Row: {
          category: string | null;
          collection_id: string | null;
          created_at: string | null;
          created_by: string | null;
          description: string | null;
          fabric_details: string | null;
          id: string;
          images: string[];
          is_active: boolean | null;
          is_new_arrival: boolean | null;
          name: string;
          price: number;
          sale_price: number | null;
          shipping_info: string | null;
          sizes: string[];
          slug: string | null;
          status: string | null;
          stock: number | null;
          stripe_payment_link: string | null;
        };
        Insert: {
          category?: string | null;
          collection_id?: string | null;
          created_at?: string | null;
          created_by?: string | null;
          description?: string | null;
          fabric_details?: string | null;
          id?: string;
          images?: string[];
          is_active?: boolean | null;
          is_new_arrival?: boolean | null;
          name: string;
          price: number;
          sale_price?: number | null;
          shipping_info?: string | null;
          sizes?: string[];
          slug?: string | null;
          status?: string | null;
          stock?: number | null;
          stripe_payment_link?: string | null;
        };
        Update: {
          category?: string | null;
          collection_id?: string | null;
          created_at?: string | null;
          created_by?: string | null;
          description?: string | null;
          fabric_details?: string | null;
          id?: string;
          images?: string[];
          is_active?: boolean | null;
          is_new_arrival?: boolean | null;
          name?: string;
          price?: number;
          sale_price?: number | null;
          shipping_info?: string | null;
          sizes?: string[];
          slug?: string | null;
          status?: string | null;
          stock?: number | null;
          stripe_payment_link?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "products_collection_id_fkey";
            columns: ["collection_id"];
            isOneToOne: false;
            referencedRelation: "collections";
            referencedColumns: ["id"];
          },
        ];
      };
      profiles: {
        Row: {
          avatar_url: string | null;
          created_at: string;
          email: string | null;
          first_name: string | null;
          id: string;
          last_name: string | null;
          phone_number: string | null;
          role: string | null;
        };
        Insert: {
          avatar_url?: string | null;
          created_at?: string;
          email?: string | null;
          first_name?: string | null;
          id: string;
          last_name?: string | null;
          phone_number?: string | null;
          role?: string | null;
        };
        Update: {
          avatar_url?: string | null;
          created_at?: string;
          email?: string | null;
          first_name?: string | null;
          id?: string;
          last_name?: string | null;
          phone_number?: string | null;
          role?: string | null;
        };
        Relationships: [];
      };
      reviews: {
        Row: {
          comment: string | null;
          created_at: string | null;
          customer_name: string;
          id: string;
          is_approved: boolean | null;
          product_id: string | null;
          rating: number | null;
          user_id: string | null;
        };
        Insert: {
          comment?: string | null;
          created_at?: string | null;
          customer_name: string;
          id?: string;
          is_approved?: boolean | null;
          product_id?: string | null;
          rating?: number | null;
          user_id?: string | null;
        };
        Update: {
          comment?: string | null;
          created_at?: string | null;
          customer_name?: string;
          id?: string;
          is_approved?: boolean | null;
          product_id?: string | null;
          rating?: number | null;
          user_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "reviews_product_id_fkey";
            columns: ["product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["id"];
          },
        ];
      };
      scanner_requests: {
        Row: {
          brand: string | null;
          created_at: string | null;
          diagnosis_result: Json | null;
          garment_type: string | null;
          id: string;
          image_url: string | null;
          input_type: string | null;
          material: string | null;
          sustainability_score: number | null;
          text_content: string | null;
          user_id: string | null;
        };
        Insert: {
          brand?: string | null;
          created_at?: string | null;
          diagnosis_result?: Json | null;
          garment_type?: string | null;
          id?: string;
          image_url?: string | null;
          input_type?: string | null;
          material?: string | null;
          sustainability_score?: number | null;
          text_content?: string | null;
          user_id?: string | null;
        };
        Update: {
          brand?: string | null;
          created_at?: string | null;
          diagnosis_result?: Json | null;
          garment_type?: string | null;
          id?: string;
          image_url?: string | null;
          input_type?: string | null;
          material?: string | null;
          sustainability_score?: number | null;
          text_content?: string | null;
          user_id?: string | null;
        };
        Relationships: [];
      };
      site_analytics: {
        Row: {
          created_at: string | null;
          event_type: string | null;
          id: string;
          page_path: string | null;
          visitor_id: string | null;
        };
        Insert: {
          created_at?: string | null;
          event_type?: string | null;
          id?: string;
          page_path?: string | null;
          visitor_id?: string | null;
        };
        Update: {
          created_at?: string | null;
          event_type?: string | null;
          id?: string;
          page_path?: string | null;
          visitor_id?: string | null;
        };
        Relationships: [];
      };
      subscribers: {
        Row: {
          active: boolean;
          created_at: string;
          email: string;
          id: string;
          name: string;
          phone: string;
          source: string | null;
          status: string | null;
          token: string;
        };
        Insert: {
          active?: boolean;
          created_at?: string;
          email: string;
          id?: string;
          name: string;
          phone: string;
          source?: string | null;
          status?: string | null;
          token?: string;
        };
        Update: {
          active?: boolean;
          created_at?: string;
          email?: string;
          id?: string;
          name?: string;
          phone?: string;
          source?: string | null;
          status?: string | null;
          token?: string;
        };
        Relationships: [];
      };
      user_roles: {
        Row: {
          created_at: string;
          id: string;
          role: Database["public"]["Enums"]["app_role"];
          user_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          role: Database["public"]["Enums"]["app_role"];
          user_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          role?: Database["public"]["Enums"]["app_role"];
          user_id?: string;
        };
        Relationships: [];
      };
      wishlists: {
        Row: {
          created_at: string;
          id: string;
          product_id: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          product_id: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          product_id?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "wishlists_product_id_fkey";
            columns: ["product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      has_role: {
        Args: {
          _role: Database["public"]["Enums"]["app_role"];
          _user_id: string;
        };
        Returns: boolean;
      };
    };
    Enums: {
      app_role: "admin" | "user";
    };
    CompositeTypes: { [_ in never]: never };
  };
};
