// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error(
    "ERRORE: Variabili Supabase mancanti. Verifica il tuo file .env.\n" +
    "Assicurati di avere VITE_SUPABASE_URL e VITE_SUPABASE_ANON_KEY settate correttamente."
  );
}

// Inizializzazione sicura del client Supabase
// Se le chiavi mancano, usiamo stringhe vuote per evitare crash immediati,
// ma le chiamate API falliranno (gestito silenziosamente dai componenti)
export const supabase = createClient<Database>(
  SUPABASE_URL || "https://placeholder.supabase.co",
  SUPABASE_ANON_KEY || "placeholder-key",
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);